from app.schemas.entities import HomeSummary, Project, Publication, ResearchUnit, Researcher


PUBLICATIONS = [
    Publication(
        id=1,
        title="Factores asociados a desenlaces cardiovasculares en pacientes asegurados con diabetes tipo 2",
        authors=["Mariana Torres", "Luis Quispe", "Ana Valdivia"],
        affiliation="Hospital Nacional Edgardo Rebagliati Martins",
        orcid="0000-0002-1845-0097",
        year=2025,
        journal="Revista Peruana de Medicina Experimental y Salud Publica",
        quartile="Q2",
        doi="10.17843/rpmesp.2025.421.10101",
        pmid="38900121",
        impact_factor=3.1,
        study_type="Cohorte retrospectiva",
        thematic_area="Enfermedades cronicas",
        funding="IETSI - Fondo concursable institucional",
        open_access=True,
        citations=18,
        altmetrics=42,
        keywords=["diabetes", "cardiologia", "cohorte", "EsSalud"],
    ),
    Publication(
        id=2,
        title="Efectividad de una estrategia de telemonitoreo para hipertension arterial en redes asistenciales",
        authors=["Rosa Medina", "Carlos Huaman", "Patricia Rojas"],
        affiliation="Red Prestacional Almenara",
        orcid="0000-0003-2019-8841",
        year=2024,
        journal="BMJ Open",
        quartile="Q1",
        doi="10.1136/bmjopen-2024-080112",
        pmid="37765498",
        impact_factor=4.0,
        study_type="Ensayo pragmatico",
        thematic_area="Salud digital",
        funding="Cooperacion internacional",
        open_access=True,
        citations=31,
        altmetrics=96,
        keywords=["telemedicina", "hipertension", "implementacion"],
    ),
    Publication(
        id=3,
        title="Perfil microbiologico y resistencia antimicrobiana en unidades criticas de hospitales nacionales",
        authors=["Jorge Salazar", "Elena Bustamante", "Victor Chang"],
        affiliation="Hospital Nacional Guillermo Almenara Irigoyen",
        orcid="0000-0001-7788-1200",
        year=2023,
        journal="Lancet Regional Health - Americas",
        quartile="Q1",
        doi="10.1016/j.lana.2023.100500",
        pmid="36678219",
        impact_factor=7.4,
        study_type="Vigilancia multicentrica",
        thematic_area="Enfermedades infecciosas",
        funding="Recursos ordinarios",
        open_access=True,
        citations=74,
        altmetrics=150,
        keywords=["resistencia antimicrobiana", "UCI", "vigilancia"],
    ),
]

PROJECTS = [
    Project(
        id=1,
        code="ESS-IETSI-2026-001",
        title="Modelo predictivo para priorizacion de riesgo cardiovascular en asegurados adultos",
        principal_investigator="Mariana Torres",
        co_investigators=["Luis Quispe", "Ana Valdivia", "Diego Fernandez"],
        unit="Unidad de Investigacion Cardiometabolica Rebagliati",
        status="En ejecucion",
        thematic_line="Inteligencia artificial en salud",
        funding_source="Fondo institucional IETSI",
        amount=420000,
        start_date="2026-02-01",
        end_date="2027-01-31",
        ethics_committee="CIEI Rebagliati",
        expected_outputs=["Articulo Q1", "Tablero de riesgo", "Guia de implementacion"],
        sdgs=["ODS 3", "ODS 9"],
        results="Validacion interna completada con historias clinicas anonimizadas.",
        pipeline_stage="Ejecucion",
    ),
    Project(
        id=2,
        code="ESS-IETSI-2025-019",
        title="Implementacion de teleconsulta especializada para pacientes con enfermedad renal cronica",
        principal_investigator="Rosa Medina",
        co_investigators=["Carlos Huaman", "Natalia Flores"],
        unit="Red Prestacional Almenara",
        status="Analisis",
        thematic_line="Servicios de salud y acceso",
        funding_source="Cooperacion tecnica",
        amount=285000,
        start_date="2025-05-15",
        end_date="2026-08-30",
        ethics_committee="CIEI Almenara",
        expected_outputs=["Informe de evaluacion", "Publicacion indexada", "Manual operativo"],
        sdgs=["ODS 3", "ODS 10"],
        results="Cohorte de seguimiento cerrada; analisis economico en curso.",
        pipeline_stage="Analisis",
    ),
    Project(
        id=3,
        code="ESS-IETSI-2026-014",
        title="Red nacional de vigilancia de infecciones asociadas a la atencion de salud",
        principal_investigator="Jorge Salazar",
        co_investigators=["Elena Bustamante", "Victor Chang", "Maria Paredes"],
        unit="Centro de Investigacion en Enfermedades Infecciosas",
        status="Aprobacion etica",
        thematic_line="Seguridad del paciente",
        funding_source="Recursos ordinarios",
        amount=510000,
        start_date="2026-07-01",
        end_date="2027-12-31",
        ethics_committee="CIEI Nacional EsSalud",
        expected_outputs=["Repositorio de vigilancia", "Reporte nacional", "Articulo multicentrico"],
        sdgs=["ODS 3"],
        results="Protocolo armonizado y diccionario de datos aprobado por el equipo tecnico.",
        pipeline_stage="Aprobacion etica",
    ),
]

RESEARCHERS = [
    Researcher(
        id=1,
        name="Dra. Mariana Torres Salcedo",
        orcid="0000-0002-1845-0097",
        renacyt="Nivel III",
        specialty="Endocrinologia",
        academic_degrees=["Doctora en Salud Publica", "Magister en Epidemiologia Clinica"],
        affiliation="Hospital Nacional Edgardo Rebagliati Martins",
        research_lines=["Enfermedades cronicas", "Analitica predictiva", "Calidad asistencial"],
        keywords=["diabetes", "riesgo cardiovascular", "machine learning"],
        methodologies=["Cohortes", "Modelamiento predictivo", "Big data clinica"],
        scientific_output=64,
        publications=38,
        citations=812,
        h_index=16,
        international_collaboration=True,
        project_leadership=5,
        collaboration_network={"nodes": 18, "national": 12, "international": 6},
    ),
    Researcher(
        id=2,
        name="Dr. Jorge Salazar Rivas",
        orcid="0000-0001-7788-1200",
        renacyt="Nivel II",
        specialty="Infectologia",
        academic_degrees=["Doctor en Medicina", "Magister en Investigacion Clinica"],
        affiliation="Hospital Nacional Guillermo Almenara Irigoyen",
        research_lines=["Resistencia antimicrobiana", "IAAS", "Vigilancia epidemiologica"],
        keywords=["antimicrobianos", "UCI", "vigilancia"],
        methodologies=["Vigilancia multicentrica", "Secuenciamiento", "Estudios transversales"],
        scientific_output=72,
        publications=44,
        citations=1240,
        h_index=21,
        international_collaboration=True,
        project_leadership=7,
        collaboration_network={"nodes": 24, "national": 15, "international": 9},
    ),
    Researcher(
        id=3,
        name="Mg. Rosa Medina Alvarez",
        orcid="0000-0003-2019-8841",
        renacyt="Nivel IV",
        specialty="Gestion de servicios de salud",
        academic_degrees=["Magister en Salud Publica", "Especialista en Gestion Sanitaria"],
        affiliation="Red Prestacional Almenara",
        research_lines=["Salud digital", "Acceso a servicios", "Evaluacion economica"],
        keywords=["telemedicina", "implementacion", "redes asistenciales"],
        methodologies=["Ensayos pragmaticos", "Metodos mixtos", "Evaluacion economica"],
        scientific_output=39,
        publications=22,
        citations=410,
        h_index=11,
        international_collaboration=False,
        project_leadership=4,
        collaboration_network={"nodes": 13, "national": 11, "international": 2},
    ),
]

UNITS = [
    ResearchUnit(
        id=1,
        name="Unidad de Investigacion Cardiometabolica Rebagliati",
        unit_type="Unidad hospitalaria",
        care_network="Red Prestacional Rebagliati",
        region="Lima",
        status="Activa",
        description="Unidad orientada a estudios clinicos y analitica poblacional en enfermedades cronicas.",
        research_lines=["Diabetes", "Riesgo cardiovascular", "Modelos predictivos"],
        linked_researchers=28,
        publications=86,
        projects=12,
        clinical_trials=3,
        infrastructure=["Biobanco", "Data mart clinico", "Sala de monitoreo"],
        productivity=92.5,
        collaborations=["UPCH", "INS", "Universidad de Sao Paulo"],
        internal_ranking=1,
    ),
    ResearchUnit(
        id=2,
        name="Centro de Investigacion en Enfermedades Infecciosas",
        unit_type="Centro especializado",
        care_network="Red Prestacional Almenara",
        region="Lima",
        status="Activa",
        description="Centro de referencia para vigilancia de infecciones y resistencia antimicrobiana.",
        research_lines=["IAAS", "Resistencia antimicrobiana", "Genomica microbiana"],
        linked_researchers=22,
        publications=74,
        projects=9,
        clinical_trials=5,
        infrastructure=["Laboratorio BSL-2", "Plataforma de vigilancia", "Secuenciador"],
        productivity=88.1,
        collaborations=["CDC Peru", "OPS", "Universidad de Chile"],
        internal_ranking=2,
    ),
    ResearchUnit(
        id=3,
        name="Nodo de Innovacion y Salud Digital Arequipa",
        unit_type="Nodo regional",
        care_network="Red Asistencial Arequipa",
        region="Arequipa",
        status="En fortalecimiento",
        description="Nodo regional para evaluacion de soluciones digitales y continuidad de cuidados.",
        research_lines=["Salud digital", "Telemonitoreo", "Gestion de redes"],
        linked_researchers=14,
        publications=31,
        projects=7,
        clinical_trials=1,
        infrastructure=["Sala de simulacion", "Mesa de interoperabilidad", "Repositorio regional"],
        productivity=76.4,
        collaborations=["UNSA", "Gobierno Regional de Arequipa"],
        internal_ranking=5,
    ),
]

HOME_SUMMARY = HomeSummary(
    kpis=[
        {"label": "Publicaciones indexadas", "value": "1,284", "trend": "+18% anual"},
        {"label": "Proyectos activos", "value": "146", "trend": "+22 nuevos"},
        {"label": "Investigadores registrados", "value": "612", "trend": "78 RENACYT"},
        {"label": "Unidades de investigacion", "value": "34", "trend": "18 regiones"},
        {"label": "Ensayos clinicos", "value": "27", "trend": "9 multicentricos"},
        {"label": "Financiamiento captado", "value": "S/ 18.6M", "trend": "+31%"},
    ],
    trends=[
        {"label": "Salud digital", "value": 82},
        {"label": "Enfermedades cronicas", "value": 76},
        {"label": "IAAS y antimicrobianos", "value": 68},
        {"label": "Oncologia", "value": 54},
        {"label": "Gestion sanitaria", "value": 49},
    ],
    news=[
        {"title": "Convocatoria de proyectos multicentricos 2026", "date": "2026-06-01", "type": "Convocatoria"},
        {"title": "Nuevo tablero de produccion cientifica por redes asistenciales", "date": "2026-05-18", "type": "Transparencia"},
        {"title": "IETSI abre registro nacional de lineas de investigacion", "date": "2026-05-06", "type": "Institucional"},
    ],
    map_regions=[
        {"region": "Lima", "units": 14, "projects": 68},
        {"region": "Arequipa", "units": 3, "projects": 12},
        {"region": "La Libertad", "units": 2, "projects": 9},
        {"region": "Cusco", "units": 2, "projects": 7},
        {"region": "Piura", "units": 2, "projects": 8},
    ],
)


def filter_items(items: list, query: str | None, fields: list[str]) -> list:
    if not query:
        return items
    needle = query.lower()
    result = []
    for item in items:
        blob = " ".join(str(getattr(item, field, "")) for field in fields).lower()
        if needle in blob:
            result.append(item)
    return result
